const provAndCities = {
    "Punjab": [
        "Bahawalnagar", "Chishtian", "Fort Abbas", "Haroonabad", "Minchinabad",
        "Ahmadpur East", "Bahawalpur", "Bahawalpur Saddar", "Hasilpur", "Khairpur Tamewali", "Yazman",
        "Khanpur", "Liaqatpur", "Rahim Yar Khan", "Sadiqabad",
        "Dera Ghazi Khan", "De-Excluded Area D.G. Khan", "Kot Chutta",
        "Jampur", "Muhammadpur", "Dajal", "Tribal Area",
        "Kot Addu", "Chowk Sarwar Shaheed",
        "Chaubara", "Karor Lal Esan", "Layyah",
        "Alipur", "Jatoi", "Muzaffargarh",
        "Rajanpur", "Rojhan", "De-Excluded Area Rajanpur",
        "Taunsa", "Koh-e-Suleman", "Vehova",
        "Bhowana", "Chiniot", "Lalian",
        "Chak Jhumra", "Faisalabad", "Faisalabad Sadar", "Jaranwala", "Samundri", "Tandlianwala",
        "Jhang", "Shorkot", "Ahmadpur Sial", "Athara Hazari", "Mandi Shah Jeewna",
        "Gojra", "Kamalia", "Pirmahal", "Toba Tek Singh",
        "Gujrat", "Kharian", "Sarai Alamgir", "Jalalpur Jattan", "Kunjah",
        "Hafizabad", "Pindi Bhattian",
        "Malakwal", "Mandi Bahauddin", "Phalia",
        "Wazirabad", "Ali Pur Chatta",
        "Gujranwala", "Gujranwala Saddar", "Kamoke", "Nowshera Virkan",
        "Narowal", "Shakargarh", "Zafarwal",
        "Daska", "Pasrur", "Sambrial", "Sialkot",
        "Chunian", "Kasur", "Kot Radha Kishan", "Pattoki",
        "Lahore Cantonment", "Lahore", "Model Town", "Raiwind", "Shalimar",
        "Nankana Sahib", "Sangla Hill", "Shah Kot",
        "Ferozewala", "Muridke", "Safdarabad", "Sheikhupura", "Sharak Pur",
        "Jahanian", "Kabirwala", "Khanewal", "Mian Channu",
        "Dunyapur", "Kahror Pacca",
        "Lodhran", "Jalalpur Pirwala", "Multan", "Multan Saddar", "Shujabad",
        "Burewala", "Mailsi", "Vehari",
        "Attock", "Fateh Jang", "Hassan Abdal", "Hazro", "Jand", "Pindi Gheb",
        "Chakwal", "Choa Saidan Shah", "Kallar Kahar",
        "Dina", "Jhelum", "Pind Dadan Khan", "Sohawa",
        "Rawalpindi", "Gujar Khan", "Kahuta", "Kallar Syedan", "Taxila", "Daultala",
        "Kotli Sattian", "Murree",
        "Depalpur", "Okara", "Renala Khurd",
        "Arifwala", "Pakpattan",
        "Chichawatni", "Sahiwal",
        "Khushab", "Noorpur Thal", "Quaidabad", "Naushera",
        "Bhalwal", "Bhera", "Kot Momin", "Sahiwala", "Sargodha", "Shahpur", "Sillanwali",
        "Bhakkar", "Darya Khan", "Kaloorkot","Mankera" , "Isakhel","Mianwali","Piplan","Talagang","Lawa"
      ]
      ,
    "Sindh":  [
        "Badin", "Khoski", "Matli", "Shaheed Fazil Rahu", "Talhar", "Tando Bago",
        "Jati", "Kharo Chan", "Mirpur Bathoro", "Shah Bandar", "Sujawal",
        "Ghorabari", "Keti Bunder", "Mirpur Sakro", "Thatta",
        "Dadu", "Johi", "Khairpur Nathan Shah", "Mehar",
        "Hyderabad", "Latifabad", "Qasimabad",
        "Kotri", "Sehwan", "Manjhand", "Thana Bulla Khan",
        "Hala", "Matiari", "Saeedabad",
        "Chamber", "Jhando Mari", "Tando Allahyar", "Nasarpur",
        "Bulri Shah Karim", "Tando Ghulam Hyder", "Tando Mohammad Khan",
        "Gulberg Town", "Liaquatabad Town", "New Karachi Town", "North Nazimabad Town", "Nazimabad",
        "Gulistan-e-Jouhar", "Gulshan Town", "Jamshed Town", "Ferozabad", "Gulshan-E-Iqbal", "Gulzar-E-Hijri",
        "Lyari Town", "Saddar Town", "Aram Bagh", "Civil Line", "Garden",
        "Orangi Town", "Manghopir", "Maripur", "Mominabad", "Ittehad town", "Baldia town",
        "Korangi Town", "Landhi Town", "Shah Faisal Town", "Model Colony",
        "Bin Qasim Town", "Gadap Town", "Malir Town", "Jinnah", "Ibrahim Hyderi", "Murad Memon", "Shah Murad",
        "Keamari Town", "Baldia Town", "S.I.T.E. Town", "Karachi Fish Harbour",
        "Garhi Khairo", "Jacobabad", "Thul",
        "Kandhkot", "Kashmore", "Tangwani",
        "Bakrani", "Dokri", "Larkana", "Ratodero",
        "Mirokhan", "Nasirabad", "Qambar", "Qubo Saeed Khan", "Shahdadkot", "Sijawal Junejo", "Warah",
        "Garhi Yasin", "Khanpur", "Lakhi", "Shikarpur",
        "Digri", "Jhuddo", "Kot Ghulam Muhammad", "Mirpur Khas", "Shujabad", "Sindhri",
        "Chachro", "Dahli", "Diplo", "Kaloi", "Islamkot", "Mithi", "Nagarparkar",
        "Kunri", "Pithoro", "Samaro", "Umerkot",
        "Daharki", "Ghotki", "Khangarh", "Mirpur Mathelo", "Ubauro",
        "Faiz Ganj", "Gambat", "Khairpur Mirs", "Kingri", "Kot Diji", "Nara", "Sobho Dero", "Thari Mirwah",
        "New Sukkur", "Pano Aqil", "Rohri", "Salehpat", "Sukkur",
        "Bhiria", "Kandiaro", "Mehrabpur", "Moro", "Naushahro Feroze Taluka",
        "Daulatpur", "Daur", "Nawabshah", "Sakrand",
        "Jam Nawaz Ali", "Khipro", "Sanghar", "Shahdadpur", "Sinjhoro", "Tando Adam Khan"
      ],
    "Khyber Pakhtunkhwa":  [
        "Bannu Tehsil", "Domel Tehsil", "Kakki Tehsil", "Baka Khel Tehsil", "Meryan Tehsil", "Wazir Tehsil", "Gumatti",
        "Lakki Marwat Tehsil", "Sari Naurang Tehsil", "Ghazni Khel Tehsil", "Bettani Tehsil", "Chichindai Kalai",
        "Datta Khel Tehsil", "Dossali Tehsil", "Gharyum Tehsil", "Ghulam Khan Tehsil", "Mir Ali Tehsil", "Miran Shah Tehsil", "Razmak Tehsil", "Shewa Tehsil", "Spinwam Tehsil",
        "Dera Ismail Khan", "Daraban Tehsil", "Kulachi Tehsil", "Paharpur Tehsil", "Paroa Tehsil", "Darazinda Tehsil",
        "Wana Tehsil", "Toi Khulla Tehsil", "Birmil Tehsil", "Serwekai Tehsil",
        "Makin Tehsil", "Tiarza Tehsil", "Ladha Tehsil", "Sararogha Tehsil", "Shaktoi Tehsil", "Shawal Tehsil", "Sarwakai Tehsil",
        "Tank Tehsil", "Jandola Tehsil",
        "Bala Kot Tehsil", "Mansehra Tehsil", "Oghi Tehsil", "Baffa Pakhal", "Darband",
        "Abbottabad Tehsil", "Havelian Tehsil", "Lora Tehsil", "Lower Tanawal Tehsil",
        "Allai Tehsil", "Batagram Tehsil",
        "Ghazi Tehsil", "Haripur Tehsil", "Khanpur Tehsil",
        "Bankad / Ranolia Tehsil", "Pattan Tehsil",
        "Judba Tehsil", "Khander Tehsil", "Daur Maira Tehsil",
        "Dassu Tehsil", "Kandia Tehsil", "Harban Basha Tehsil", "Seo Tehsil",
        "Bataira / Kolai", "Palas",
        "Hangu Tehsil", "Tall Tehsil",
        "Karak Tehsil", "Banda Daud Shah Tehsil", "Takht-e-Nasrati Tehsil",
        "Kohat Tehsil", "Lachi Tehsil", "Gumbat Tehsil", "Dara Adam Khel Tehsil",
        "Central Kurram Tehsil", "Lower Kurram Tehsil", "Upper Kurram Tehsil",
        "Central Orakzai Tehsil", "Ismail Zai Tehsil", "Lower Orakzai Tehsil", "Upper Orakzai Tehsil",
        "Daggar Tehsil", "Gagra Tehsil", "Khudu Khel", "Mandanr Tehsil", "Gadezai", "Salarzai", "Chagharzai",
        "Bar Chamer Kand Tehsil", "Barang Tehsil", "Khar Bajaur Tehsil", "Mamund Tehsil", "Nawagai Tehsil", "Salarzai Tehsil", "Utmankhel Tehsil",
        "Buni Tehsil", "Mastuj Tehsil", "Mulkhow/Torkhow Tehsil",
        "Chitral Tehsil", "Drosh Tehsil",
        "Adenzai Tehsil", "Lal Qilla Tehsil", "Samar Bagh Tehsil", "Timergara Tehsil", "Khal Tehsil", "Balambat Tehsil", "Munda Tehsil",
        "Sam Rani Zai Tehsil", "Batkhela Tehsil", "Thana Baizai Tehsil",
        "Alpuri Tehsil", "Bisham Tehsil", "Puran Tehsil", "Chakesar Tehsil", "Martung Tehsil", "Makhuzai Tehsil",
        "Babuzai Tehsil", "Barikot Tehsil", "Behrain Tehsil", "Charbagh Tehsil", "Kabal Tehsil", "Khwaza Khela Tehsil", "Matta Tehsil",
        "Dir Tehsil", "Sharingal Tehsil", "Wari Tehsil", "Lar Jam Tehsil", "Barawal Tehsil", "Kalkot Tehsil",
        "Katlang Tehsil", "Rustam Tehsil", "Ghari Kapura Tehsil", "Mardan Tehsil", "Takht Bhai Tehsil", "Lund Khwar Tehsil",
        "Lahor Tehsil", "Razar Tehsil", "Swabi Tehsil", "Topi Tehsil",
        "Charsadda Tehsil", "Shabqadar Tehsil", "Tangi Tehsil",
        "Bara Tehsil", "Jamrud Tehsil", "Landi Kotal Tehsil", "Mula Gori Tehsil",
        "Ambar Utman Khel Tehsil", "Halim Zai Tehsil", "Pindiali Tehsil", "Pran Ghar Tehsil", "Safi Tehsil", "Upper Mohmand Tehsil", "Yake Ghund Tehsil",
        "Jehangira Tehsil", "Nowshera Tehsil", "Pabbi Tehsil",
        "Peshawar Tehsil", "Shah Alam Tehsil", "Mathra Tehsil", "Chamkani Tehsil", "Badbher Tehsil", "Peshtakhara Tehsil", "Hassan Kheil Tehsil", "Kalakhel"
      ],
   
    "Azad Kashmir":  [
        "Kotli", "Khuiratta", "Fatehpur Thakiala", "Sehnsa", "Charhoi", "Duliah Jattan",
        "Dadyal", "Mirpur", "Islamgarh",
        "Bhimber", "Barnala", "Samahni",
        "Hattian Bala", "Chikkar", "Leepa",
        "Muzaffarabad", "Nasirabad Tehsil",
        "Athmuqam", "Sharda",
        "Bagh", "Dhirkot", "Hari Ghel", "Rera", "Birpani",
        "Haveli", "Khurshidabad", "Mumtazabad",
        "Abbaspur", "Hajira", "Rawalakot", "Thorar",
        "Balouch", "Mang", "Pallandri", "Tarar Khel"
      ],
 "Balochistan" : [
    "Awaran", "Gishkaur", "Jhal Jhao", "Korak Jahoo", "Mashkay",
    "Kalat", "Mangochar", "Surab", "Gazg", "Johan",
    "Kharan", "Sar-Kharan", "Tohumulk",
    "Khuzdar", "Nall", "Wadh", "Zehri", "Baghbana", "Aranji", "Greshek", "Karkh", "Moola", "Ornach", "Saroona",
    "Hub", "Dureji", "Bela", "Kanraj", "Uthal",
    "Dasht", "Mastung", "Khad Koocha", "Kardigap",
    "Besima", "Mashkel", "Washuk", "Nag", "Shahgori",
    "Gwadar", "Jiwani", "Ormara", "Pasni", "Suntsar",
    "Mand", "Tump", "Turbat", "Balnigor", "Buleda", "Dasht", "Zamuran", "Gayab", "Solband",
    "Gowargo", "Panjgur", "Paroom", "Gichk",
    "Gandakha", "Jhatpat", "Usta Mohammad",
    "Gandawa", "Jhal Magsi", "Mirpur",
    "Dhadar", "Balanari", "Khattan", "Mach", "Sani",
    "Bhag", "Lehri",
    "Baba Kot", "Dera Murad Jamali", "Tamboo", "Chattar", "Meer Hassan Tehsil",
    "Faridabad", "Hayrvi", "Manjipur", "Sohbatpur",
    "Dalbandin", "Nokundi", "Taftan", "Chagai",
    "Chaman", "Gulistan", "Killa Abdullah", "Dobandi",
    "Nushki", "Dak",
    "Barshore", "Hurramzai", "Karezat", "Khanozai", "Pishin", "Saranan",
    "Chiltan", "Zarghoon", "Panjpai", "Sadar", "Kuchlak", "Siryab",
    "Dera Bugti", "Phelawagh", "Sui", "Baiker",
    "Harnai", "Shahrig", "Khoast",
    "Kahan", "Kohlu", "Maiwand", "Tamboo", "Grisini",
    "Sibi", "Kutmandai", "Sangan",
    "Ziarat", "Sinjavi",
    "Sherani",
    "Qamar Din Karez", "Zhob", "Ashwat", "Kashatu", "Sambaza",
    "Killa Saifullah", "Loiband", "Muslim Bagh", "Badini", "Kanmetharzai", "Shinki",
    "Barkhan"
  ],
  "Gilgit-Baltistan" : [
    "Khaplu", "Mashabrum",
    "Gultari", "Kharmang", "Rondu", "Shigar", "Skardu",
    "Shigar", // Listed again, possibly a duplication
    "Kharmang", // Listed again, possibly a duplication
    "Roundu", // Listed again with different spelling, possibly a duplication
    "Gahkoch", "Ishkoman", "Punial",
    "Gupis", "Yasin",
    "Danyour", "Gilgit", "Juglot",
    "Ali Abad", "Gojal",
    "Nagar-I", "Nagar-II",
    "Astore", "Shounter",
    "Babu Sar", "Chilas",
    "Darel", // Listed under "Darel" heading, might be a duplication
    "Tangir" // Listed under "Tangir" heading, might be a duplication
  ]  
}


export {provAndCities};


